version: "3"
services: 
    api:
        build: api
        ports: 
            - 3000:80
    nginx:
        build: server
        ports: 
            - 80:80
        restart: always
        depends_on:
            - api
        volumes:
            - ./client/dist/client:/usr/share/nginx/html